version: '3.7'

services:
  flask:
    build: .
    # depends_on:
    #   - database
    ports:
      - 5000:5001

  # database:
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_USER=cursor
  #     - POSTGRES_PASSWORD=very_secret_password
  #     - POSTGRES_DB=docker_flask_db
  #   ports:
  #     - 5432:5432